# Generated by Django 2.2.6 on 2020-04-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsPriceInfo',
            fields=[
                ('goods_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now=True)),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoodsInfo',
            fields=[
                ('openid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('begin_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=10)),
                ('goods_id', models.CharField(max_length=30)),
                ('monitor_user', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('openid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=30)),
                ('unionid', models.CharField(max_length=30)),
                ('self_session', models.CharField(default=0, max_length=40)),
                ('last_active_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMonitorCart',
            fields=[
                ('openid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('goods_list', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='UserMonitorOrderHistory',
            fields=[
                ('openid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=30)),
                ('begin_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('goods_list', models.CharField(max_length=2048)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
