# Generated by Django 3.0.5 on 2020-04-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBModel', '0003_auto_20200422_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_active_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
